/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.calcsolver;

//import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;

class CalculatorUITest {
//    @Test void appHasAGreeting() {
//       CalculatorUIp classUnderTest = newCalculatorUIp();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
}
